### ISSUE TITLE
Recent update to requirements class breaks 3.4-dev

### ISSUE THREAD

**Issue by l0rn** [bolt/requirements#1]
Hey:

34a45b3fccdafd4112ae1ed72ec17f9c9b1aa9e0

I guess we should access properties like 'paths' in a safe way... Bolt complaint not having it in my .bolt.php ...

**Comment by GwendolenLynch** [comment]
Can you give me more info on what is breaking, error message, etc?

**Comment by l0rn** [comment]
Sure, sorry 
![bildschirmfoto vom 2017-08-31 17-58-01](https://user-images.githubusercontent.com/5889030/29932916-01a9cd3a-8e76-11e7-9c76-e0e7d2b57e31.png)

Happens while my .bolt.php looks like this:
```

<?php

return [
    'extensions' => [
        new Custom\CustomExtension()

    ],
    'services' => [
        new Custom\AwsServiceProvider()
    ],
];

```

If I add a path property like


```
return [
    'extensions' => [
        new Custom\CustomExtension()

    ],
    'services' => [
        new Custom\AwsServiceProvider()
    ],
   'paths': => []
];
```

The problem goes away.... I guess $config['paths'] just needs to default to [] when not set

**Comment by GwendolenLynch** [comment]
Ah cool, thanks! I'll fix this shortly, unless you want the commit credit via the repos first PR :smile:
