### ISSUE TITLE
xdebug.max_nesting_level 

### ISSUE THREAD

**Issue by milosa** [bolt/requirements#3]
https://github.com/bolt/requirements/blob/56bc6e0fdf55f9ce8b395e667481c6955e744d02/src/BoltRequirements.php#L204-L207

Either, the check should be `$cfgValue >= 500`

Or, the help text should say `Set "<strong>xdebug.max_nesting_level</strong>" to e.g. "<strong>501</strong>" `

Because putting the level at 500 doesn't get rid of the message right now.

**Comment by GwendolenLynch** [comment]
Thanks for noticing this! Fixed in 39dfa278ed44284386e2af98cc8b04fc1d4f7710
